# Generated by Django 5.2.15 on 2026-06-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvtorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('country', models.CharField(choices=[('qaraqalpaqistan', 'Qaraqalpaqistan'), ('Uzbekistan', 'Uzbekistan')], max_length=100)),
                ('create_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('year', models.IntegerField()),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.avtormodel')),
            ],
        ),
    ]
